name: wikiman_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.6+8

environment:
  sdk: ^3.11.1

dependencies:
  file_picker: ^12.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: 10.0.0
  http: ^1.6.0
  http_parser: ^4.1.2
  path_provider: ^2.1.6
  permission_handler: 11.4.0
  record: ^6.2.1
  share_intent_package: ^1.0.32
  speech_to_text: ^7.4.0
  webview_flutter: ^4.14.1
  webview_flutter_android: ^4.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
